Initialize components
ONJoseph/Bookstore pull request #1
Opened 2022-06-03 18:55 UTC by ONJoseph

-[x] initialise React app.
-[x] create a directory for your components.
-[x] add [React Router] and set two <Route>s and <Link>s for the app's navigation:
-[x]  add Books - Should display the list of books (empty at this point but it should be ready for the data) with the Remove button (no funcionality yet).
-[x] create a component called Book for displaying a single book (receive a title and an author as prop) and reuse it in a component that displays a list of books.
-[x] add a form for adding a book (no functionality yet).
-[x] create a separate component for this form (with inputs for a title and an author).
-[x] add Categories:
- Should display a button "Check status" only.
-Styling is not required at this point.

2022-06-03 20:32 UTC, JuliCarracedo requested changes
Hi @ONJoseph , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._
- [ ] for this stage of the project, BookList is required to be able to show a list of books using a `book` component to display each individual book.
- [ ] It is a requirement to set up these react-router-dom routes to navigate to: 
   - Books
   - Categories
- [ ] and to have react-router-dom links set up to click on them and visit those pages.
- [ ] the Book component must take the data to display as a prop.
- [ ] The project must contain a form to create new books, which must have a button for submissions (it is not required to work) 
- [ ] The categories direction must show a button reading "Check Status"

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-04 00:40 UTC, Cathella requested changes
## 🟡 Status: Changes Required 🛑

### Hi @ONJoseph 👋🏻, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

![this-close-so-close](https://user-images.githubusercontent.com/4247740/171969702-a3520805-20ef-44bd-97ce-f910562d1352.gif)


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-04 00:40 UTC, Cathella commented on src/components/pages/Categories.js
> +  );
- [ ] [REQUIRED] Kindly display a button reading "Check Status" in the categories component as stated in the requirements.

2022-06-04 00:40 UTC, Cathella commented on src/components/SingleBook.js
> +/* eslint-disable camelcase */
- [ ] [REQUIRED] Kindly fix linter errors instead of disabling them. This is important in keeping high code standards.

2022-06-04 00:40 UTC, Cathella commented on src/components/Header.js
> +        </nav>
✅ Have react-router-dom links set up to click on them and visit navigation pages 👍🏻

2022-06-04 00:40 UTC, Cathella commented on src/components/Form.js
> +      </form>
✅ The project must contain a form to create new books, which must have a button for submissions 👍🏻

2022-06-04 00:40 UTC, Cathella commented on src/components/BooksList.js
> +      )}
✅ BookList is required to be able to show a list of books using a book component to display each individual book 👍🏻

2022-06-04 00:40 UTC, Cathella commented on src/App.js
> +          </Routes>
✅ Set up these react-router-dom routes to navigate to: Books and Categories 👍🏻

2022-06-04 00:40 UTC, Cathella commented on src/redux/books/booksActions.js
> +/* eslint-disable no-unused-vars */
- [ ] [REQUIRED] Kindly fix linter errors instead of disabling them. This is important in keeping high code standards.

2022-06-04 18:44 UTC, Rustamxon7 approved these changes
## Hi @ONJoseph 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉 

Cheers and Happy coding!👏👏👏

![Developer-512px-10](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-06-04 20:18 UTC, merged